
version: "3"

services:
  nginx: 
    image: nginx:latest
    container_name: lnmp_nginx
    ports:
      - "80:80"

    volumes:
      - ./www/:/usr/share/nginx/html/:rw
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: "Asia/Shanghai"

    restart: always
    networks:
      - lnmp 

  php:
    image: php:7.3.29-fpm
    container_name: lnmp_php
    volumes:
      - ./www:/var/www/html/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - lnmp

  mysql:
    image: mysql:5.6
    container_name: lnmp_mysql
    ports:
      - "3306:3306"

    volumes:
      - ./mysql/data:/var/lib/mysql/:rw
    
    restart: always
    networks:
      - lnmp

    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"
networks:
  lnmp:


    
