
version: "3"
services:
  clash:
    image: dreamacro/clash
    restart: unless-stopped
    ports:
      - 7890:7890
      - 7891:7891
      - 60005:9090
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      -  ./ui:/ui
    network_mode: "bridge"

  clash-ui:
    image: haishanh/yacd
    restart: unless-stopped
    ports:
      - 60004:80
    depends_on:
      - clash
    network_mode: "bridge"
